view:
  site:
    wxPayEnable: ${wx.pay.enable}
    needLoginArticleReadCount: 30 # 需要登录才能阅读的文章阅读次数
    zsxqArticleReadCount: 20 # 知识星球用户才能阅读的文章阅读次数统计间隔，单位：分钟
    needPayArticleReadCount: 20 # 付费文章，未付费可以看到的文章内容
    websiteName: 编程派
    websiteLogoUrl: http://127.0.0.1:${server.port}/img/logo.png
    websiteFaviconIconUrl: http://127.0.0.1:${server.port}/img/icon-my.png
    zsxqUrl: https://ss.bjmu.edu.cn/Html/News/Articles/103156.html
    zsxqImgUrl: http://serendipityspace.top/forum/image/zshb.png
    zsxqPosterUrl: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/javabetter.jpg
    contactMeTitle: 联系我 - 编程派
    contactMeWxQrCode: http://127.0.0.1:${server.port}/img/qrcode.jpg
    contactMeStarQrCode: http://127.0.0.1:${server.port}/img/geren-weixin.jpg
    #contactMeStarQrCode: https://cdn.tobebetterjavaer.com/tobebetterjavaer/images/qiye-weixin.png
    pageSize: 20
    cdnImgStyle:
    websiteRecord: 苏ICP备2025176864号-1
    wxLoginUrl: http://weixin.qq.com/r/WxwpMefE-rqBraNS90lJ
    host: http://127.0.0.1:${server.port}
    welcomeInfo: 欢迎来到技术派，戳<a href="/article/detail/15">技术派全方位视角解读</a>了解我们
    oss: